- name: Pull Docker Image from Docker Hub
  hosts: hostvm
  remote_user: iiitb
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "adithip/calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Start Docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name calculator adithip/calculator
